spring:
    application:
        name: my-day-server
    datasource:
        url: jdbc:postgresql://localhost:5432/my_day_db
        username: postgres
        password: pqkiet854
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    profiles:
        active: default

---
spring:
    config:
        activate:
            on-profile: test
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
    jpa:
        hibernate.ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true

---
logging:
    level:
        root: INFO
        '[org.springframework.security]': DEBUG
        
jwt:
    signer-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
    expiration: 900
    refresh-token-expiration: 604800