spring:
    application:
        name: my-day-server
    datasource:
        url: jdbc:postgresql://localhost:5432/my_day_db
        username: postgres
        password: pqkiet854
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        root: INFO
        '[org.springframework.security]': DEBUG
        
jwt:
    signer-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
    expiration: 900
    refresh-token-expiration: 604800